apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk
data:
  elasticsearch.yml: |
    path.repo: ["/mount/backups"]
    discovery.type: single-node
    xpack.security.enabled: false