apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.0
          ports:
            - containerPort: 5601
          env:
            - name: elasticsearch.hosts
              value: "http://elasticsearch:9200"
            - name: elasticsearch.serviceAccountToken
              value: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zeXN0ZW06YzUzMWRLUm1SVzIzMXJCTkVST0hZQQ"
            - name: xpack.security.encryptionKey
              value: "KMbIUEmceO/wCMlSv66rjKg8GTvdt4kkO4hY4Cp991E="
            - name: xpack.encryptedSavedObjects.encryptionKey
              value: "HXeldtxFPKSua7FLBP7yO/20f02Yk3SiEnyTAe2pzfU="
            - name: xpack.reporting.encryptionKey
              value: "+qJ7jH1HuQcFWRQJymsoF7Csu7tN/GoUyHSY2P4up5I="
            - name: NODE_OPTIONS
              value: "--openssl-legacy-provider=false"
