apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      file {
        path => "/usr/share/logstash/pipeline/apache-logs/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
      }
    }
    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "apache-logs-%{+YYYY.MM.dd}"
      }
    }