apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      http {
        port => 8080
      }
    }

    filter {
      if [fields][log_type] == "apache" {
        grok {
          match => { "message" => "%{COMMONAPACHELOG}" }
        }
        date {
          match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "apache-logs-%{+YYYY.MM.dd}"
      }
    }
