apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: elk
type: Opaque
data:
  elastic-username: ZWxhc3RpYw== # Base64 encoded value of "elastic"
  elastic-password: ZWxrcGFzc3dvcmQ= # Base64 encoded value of "elkpassword"