apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2tpYmFuYS9raWJhbmEtYWNjZXNzLXRva2VuOmVrcmt5ZmNUcnFrZThlM2twTzJQQQ"
    xpack.security.encryptionKey: "KMbIUEmceO/wCMlSv66rjKg8GTvdt4kkO4hY4Cp991E="
    xpack.encryptedSavedObjects.encryptionKey: "HXeldtxFPKSua7FLBP7yO/20f02Yk3SiEnyTAe2pzfU="
    xpack.reporting.encryptionKey: "+qJ7jH1HuQcFWRQJymsoF7Csu7tN/GoUyHSY2P4up5I="
    xpack.screenshotting.browser.chromium.disableSandbox: true
