apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.0
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          env:
            - name: ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: elastic-token
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: encryption-key
            - name: NODE_OPTIONS
              value: --openssl-legacy-provider=false
      volumes:
        - name: config-volume
          configMap:
            name: kibana-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    xpack.screenshotting.browser.chromium.disableSandbox: true

---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
  namespace: elk
type: Opaque
data:
  encryption-key: M2NTdHEzakhCMkEvNU9kazIwcGFoSTh6RCtOT3BHRTQ3SzRTbGxGZlhOaz0= # 3cStq3jHB2A/5Odk20pahI8zD+NOpGE47K4SllFfXNk= # Base64 encoded



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kibana
#   namespace: elk
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kibana
#   template:
#     metadata:
#       labels:
#         app: kibana
#     spec:
#       containers:
#         - name: kibana
#           image: docker.elastic.co/kibana/kibana:8.17.0
#           ports:
#             - containerPort: 5601
#           env:
#             - name: SERVER_NAME
#               value: kibana
#             - name: ELASTICSEARCH_HOSTS
#               value: http://elasticsearch:9200
#             - name: ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN
#               value: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpDNTFMdVJqWVJNeWUwVjNweXNzMHhB
#             - name: XPACK_SECURITY_ENCRYPTIONKEY
#               value: KMbIUEmceO/wCMlSv66rjKg8GTvdt4kkO4hY4Cp991E=
#             - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
#               value: HXeldtxFPKSua7FLBP7yO/20f02Yk3SiEnyTAe2pzfU=
#             - name: XPACK_REPORTING_ENCRYPTIONKEY
#               value: +qJ7jH1HuQcFWRQJymsoF7Csu7tN/GoUyHSY2P4up5I=
#             - name: NODE_OPTIONS
#               value: --openssl-legacy-provider=false
#           args:
#             - "bin/kibana"
#           resources:
#             requests:
#               memory: "2Gi"
#               cpu: "500m"
#             limits:
#               memory: "4Gi"
#               cpu: "1"
#           volumeMounts:
#             - name: kibana-config
#               mountPath: /usr/share/kibana/config/kibana.yml
#               subPath: kibana.yml
#       volumes:
#         - name: kibana-config
#           configMap:
#             name: kibana-config
